### ISSUE TITLE
Problems with switching mode

### ISSUE THREAD

**Issue by zhanghanghitomi** [aidenlx/media-extended#159]
I have a md file that has some time stamps.  First, I switch to view mode to click the link of the time stamp. When I switch back to the editing mode to take notes, a weird thing happens: the video window keeps shrinking.

**Comment by wenbopeng** [comment]
> 

same question

**Comment by jasonfeidt** [comment]
Yes, for me there are always more tabs opening when switching modes when using timestamps, which makes the video also smaler and the feature unusable.

**Comment by HaroldCheung** [comment]
same problem! after the new version of obsidian

**Comment by PetrusZ** [comment]
Yeah, same issue here. I thought it was my prolblem before.

**Comment by kokokoala** [comment]
same problem here.

**Comment by twiceyuan** [comment]
Same issue here. 

Obsidian version:Version 0.15.9 (installer 0.15.9)
Extension verison: 2.11.1

**Comment by zhanghanghitomi** [comment]
It appears this problem won't be solved in short time. I find a substitute plugin called timestamp notes.

**Comment by fxrcode** [comment]
same issue. Everytime I switch mode, more tab stacked to the video tab...

**Comment by Darkbluetest** [comment]
Yes, this is the same (Obisidan 1.0.3, Media Extended 2.11.1), no way to edit anything. The only workaround, it is not: to turn off the "Timestamps for Media" option, and only be able to use timestamps for playing back embeds...which is a pity and you lost half of interest on the plugin. I hope it will be fixed soon.

**Comment by TearOnly** [comment]
A workaround to avoid opening all of these unwanted tabs under the video while switching from reading to editing to take timestamps is:
1. Open the video with media extended as usual (one tab has the note and the other tab has the media extended video)
2. Unlink the video tab (it's linked with the note tab to be able to get timestamps)
3. Switch to editing mode on the note 
4. Link the note to the video again otherwise you won't be able to get the timestamps
5. Play the video and take all the timestamps at once without switching to reading at all

~ Obsidian v1.1.8 - Installer v0.15.8 - Media extended v2.11.1
Not the best workaround but for now it's better than nothing, I hope it helps.
Looking forward to a fix, this plugin is excellent ~

**Comment by GianBM87** [comment]
This is a free tool, so we shouldn't ask too much.
I studied the code and the problem in action and it seems to be triggered by an outdated function who send both the media and the note. i still can't spot where the problem is, but it should be when returning the "this.leaf" element. So the solution is to add a code to remove the div that include the linked note, as spotted by "TearOnly", but it could be a lot of work and pain to fix it, since I'm not used to obsidian api.

And also, i found an easier solution to manipulate obsidian dom. If you didn't understand what i said, simply paste this code in a CSS snippet:
`
.workspace-leaf-content[data-type="media-view"] ~ .workspace-leaf-content[data-type="markdown"] { display:none;
}`
it simply hide what i spotted above, it hide the extra leaf nodes generated when switching mode. (the video is this leaf with data-type="media-view", and ~ select all elemnts below that leaf, in this case with the format  .workspace-leaf-content[data-type="markdown"] which is the format of the generated notes below the video)

there are issues that must be considered. when you switch mode, the extra note is only hidden, which means that it still is in obsidian consuming space, so if you switch mode when editing your note 100 times, it will create 100 hidden notes. I guess if you have a potato pc, it will affect performance. Closing the video also close those notes, so if you see some performance problems, only refresh the video.

also it can affect other plugin, which uses data-type="media-view" elements, so you are warned.

i tested this in my workflow and work fine in my use case.

**Comment by TearOnly** [comment]
I found another workaround with an obsidian plugin called "Hover editor" by NothingIsLost, while note and video are open with Obsidian, simply open the note you want to edit with the hover editor plugin by right-clicking on the note and "open in hover editor".

**Comment by marsvet** [comment]
This is a elegant solution: https://github.com/aidenlx/media-extended/issues/151#issuecomment-1473046813

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.
