### ISSUE TITLE
Timestamp local file above 1 hour

### ISSUE THREAD

**Issue by gmmazza** [aidenlx/media-extended#38]
Local files timestamps above 1 hour, fails to take all the reference and only get the first number.  Tried in a new vault with all default except the media-extended plugin.

**Comment by AidenLx** [comment]
Could you give me a screen recording of how this bug occur? Seems to be working fine here. 

https://user-images.githubusercontent.com/31102694/119517504-41be1b80-bdaa-11eb-953e-6616fbee361f.mp4

**Comment by gmmazza** [comment]
Here is the recording. Added the video dropping it in the page of obsidian.

https://user-images.githubusercontent.com/29898425/119771818-a6ee3b80-be94-11eb-98ba-64c7c9f28aaf.mp4

**Comment by AidenLx** [comment]
Does this bug occur in YouTube videos as well?

**Comment by gmmazza** [comment]
No, YouTube shows the timestamp in seconds. Like your video. (you can see links to the YouTube above the links that I screen recorded is doing it right)

**Comment by AidenLx** [comment]
I was not be able to reproduce this: 
![image](https://user-images.githubusercontent.com/31102694/120067654-50107e00-c0af-11eb-80f9-6932b69b87ef.png)
automatically turn into 
![image](https://user-images.githubusercontent.com/31102694/120067660-5999e600-c0af-11eb-96db-74e8a4d4a536.png)

But the problem with `hh:mm:ss` not being recognized properly should be fixed in v2.7.2 now

**Comment by gmmazza** [comment]
yes, that happens, you can see that behaviour in the screen record I send.
Updated to v2.7.2 and the link preview mode is properly shown, but the link to player still not works, opens the video in second 1, either in edit or preview mode.

**Comment by AidenLx** [comment]
Can you check if this is fixed in Obsidian v0.12.5? It fixes a bug described in #41. If it still happens, could you check if you have any emoji-related plugins installed?
